### ISSUE TITLE
Is it possible to skip chrome cookie reading when chrome is not installed?

### ISSUE THREAD

**Issue by kgfly** [clearloop/leetcode-cli#100]
On the system, where this is no GUI, such as Ubuntu server or Windows subsystem for Linux, there is no chrome. leetcode_cli hit this error:

[INFO  leetcode_cli::cfg] Generate root dir at "/home/z/.leetcode".
thread 'main' panicked at 'Error connecting to "/home/z/.config/google-chrome/Default/Cookies"', /home/z/.cargo/registry/src/github.com-1ecc6299db9ec823/leetcode-cli-0.3.11/src/cache/mod.rs:17:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Is it possible to skip chrome cookie reading when chrome is not installed?

Instead, the application reads cookie info directly from ~\.leetcode\leetcode.toml

Thanks.

**Comment by wendajiang** [comment]
Actually you can set 
```toml
[cookies]
csrf = 'your/csrftoken'
session = 'your/session'
```
in $HOME/.leetcode/leetcode.toml, and the leetcode-cli would not auto check the Chrome token.

Refer to https://github.com/wendajiang/leetcode-cli#cookies.
