### ISSUE TITLE
Acquire session and csrf token on Chrome 108

### ISSUE THREAD

**Issue by heeh** [clearloop/leetcode-cli#102]
It seems that the following command no longer works on Chrome 108.0.5359.94. 
The following command redirect a browser to `chrome://settings`.
`chrome://settings/cookies/detail?site=leetcode.com`

Has anyone been able to acquire `session` and `csrf` token on the recent Chrome?

**Comment by wendajiang** [comment]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/13445879/207077611-857cc073-303f-472e-853e-c15361f18c7a.png">
My environment is MacBook Arm version, and the Chrome version is > 108, and is work correctly.
Can you offer your environment in detail?

**Comment by heeh** [comment]
Thanks for your reply. It's Ubuntu 22.04 and the result looks like this:
![image](https://user-images.githubusercontent.com/5158322/207298689-6032db4a-dcf2-4326-b4a7-61a039f64ec7.png)

**Comment by heeh** [comment]
Figured it out. It seems that the recent chrome hid this menu for some reasons. Try this:

1. Log in leetcode.com in chrome
2. Open chrome developer tools (F12)
3. Click `application`
4. Expand `storage->cookies`
5. Copy and paste `csrftoken` and `LEETCODE_SESSION`
