### ISSUE TITLE
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)' when piping

### ISSUE THREAD

**Issue by xiaoxiae** [clearloop/leetcode-cli#21]
The program doesn't seem to handle broken pipes well. When doing 
```sh
leetcode list -q eLD | head -n 1
```
to get the next easy unlocked problem that I haven't solved, the following happens:
```
        [ 122] Best Time to Buy and Sell Stock II                           Easy   (57.55 %)
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:993:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Googling around, [this might be of use](https://willmurphyscode.net/2017/08/30/broken-pipe/).

**Comment by clearloop** [comment]
> ```shell
> leetcode list -q eLD | head -n 1
> ```

This usage is awesome, I haven't implemented pipe when I wrote this repo, we can support this by redirecting the print information to standard [stdout][stdout].

For example, modify this

https://github.com/clearloop/leetcode-cli/blob/0d68c73ba3bee3547c9955c75773756db011ffe6/src/cmds/list.rs#L171-L173

to this 

```rust
io::stdout().write_all(ps.join("\n").as_bytes)?;
```

I'll do this upgrade this tomorrow, nice shot!

[stdout]: https://doc.rust-lang.org/std/io/fn.stdout.html
