### ISSUE TITLE
feature request: support concurrecy category

### ISSUE THREAD

**Issue by frrad** [clearloop/leetcode-cli#29]
I can't see problems from the concurrency category https://leetcode.com/problemset/concurrency/

editing `leetcode.toml` to include this category in the categories list results in the following error:

```
error: invalid length 4, expected 3 elements in sequence for key `sys.categories` at line 55 co
lumn 1, Parse config file failed, leetcode-cli has just generated a new leetcode.toml at ~/.lee
tcode/leetcode_tmp.toml, the current one at ~/.leetcode/leetcode.tomlseems missing some keys, p
lease compare to the tmp one and add them up : )
.
```

**Comment by clearloop** [comment]
The problem is https://github.com/clearloop/leetcode-cli/blob/dc19d2af697b6132479357d9b5fc7c4533211183/src/cfg.rs#L102,

We can change `pub categories: [String; 3]` to `pub categories: Vec<String>`,  to fix this problem~

**Comment by frrad** [comment]
I've never touched rust before / don't know how to verify that this even compiles but https://github.com/clearloop/leetcode-cli/pull/31 implements the change you suggested

**Comment by clearloop** [comment]
> I've never touched rust before / don't know how to verify that this even compiles but #31 implements the change you suggested

After [installing rust](https://www.rust-lang.org/tools/install) on your machine, just run `cargo run` under the directory of this repo, welcome to the rust family, it's the best programming language ;)
