### ISSUE TITLE
Cannot read locked problem (premium account)

### ISSUE THREAD

**Issue by heeh** [clearloop/leetcode-cli#35]
Thanks for great work. The program is blazing fast and I like it.
Currently, `leetcode-cli` cannot retrieve the locked problems for premium account.
Is there a solution for this?

**Comment by clearloop** [comment]
> Currently, leetcode-cli cannot retrieve the locked problems for premium accounts.

Sorry, I thought the locked problems will be fetched automatically since you login into leetcode.com with a premium account before.

If somebody wants to implement this, ping me if I can help

**Comment by Raees678** [comment]
I've created a PR for this. It adds support for premium Leetcode questions (although I'm not sure how it will behave for users who don't have Leetcode premium.

**Comment by heeh** [comment]
@Raees678 It just worked! Thank you so much.

**Comment by clearloop** [comment]
Hi @heeh, how do you like a flag like `-l` to show the locked problems for the premium accounts?

**Comment by clearloop** [comment]
Merged #36.

Use leetcode-cli `v0.3.6`
