### ISSUE TITLE
cannot find type `NoneError` in module `std::option`

### ISSUE THREAD

**Issue by heeh** [clearloop/leetcode-cli#37]
System: 
`Ubuntu 20.04 on wsl2`
Issue: 
`The program does not compile any more. I guess this has something to do with nightly build.`
` rustc 1.54.0-nightly (ff2c947c0 2021-05-25)`
log:
```
error[E0412]: cannot find type `NoneError` in module `std::option`
   --> src/err.rs:118:38
    |
118 | impl std::convert::From<std::option::NoneError> for Error {
    |                                      ^^^^^^^^^ not found in `std::option`

error[E0412]: cannot find type `NoneError` in module `std::option`
   --> src/err.rs:119:29
    |
119 |     fn from(_: std::option::NoneError) -> Self {
    |                             ^^^^^^^^^ not found in `std::option`

error[E0277]: the `?` operator can only be used on `Result`s, not `Option`s, in an async function that returns `Result`
  --> src/plugins/leetcode.rs:75:29
   |
69 |       pub async fn get_category_problems(self, category: &str) -> Result<Response, Error> {
   |  _________________________________________________________________________________________-
70 | |         trace!("Requesting {} problems...", &category);
71 | |         let url = &self
72 | |             .conf
...  |
75 | |             .get("problems")?
   | |                             ^ use `.ok_or(...)?` to provide an error compatible with `Result<Response, err::Error>`
...  |
88 | |         .await
89 | |     }
   | |_____- this function returns a `Result`
   |
   = help: the trait `FromResidual<std::option::Option<Infallible>>` is not implemented for `Result<Response, err::Error>`
   = note: required by `from_residual`
(85 errors)
```

**Comment by heeh** [comment]
I was able to compile the program using the previous nightly version(2021-05-16).
However, it would be great if this program does not depend on the specific nightly version.

**Comment by clearloop** [comment]
> I was able to compile the program using the previous nightly version(2021-05-16).
> However, it would be great if this program does not depend on the specific nightly version.

Thanks for ur report @heeh !!, I'll fix this this weekend~

**Comment by heeh** [comment]
By the way, I think this is the best leetcode cli program in the present.
There are also dependencies. 
The README does not explicitly mention this and new users with little experience might be confused.
```
gcc
libssl-dev
libdbus-1-dev
libsqlite3-dev
```

**Comment by clearloop** [comment]
> The README does not explicitly mention this and new users with little experience might be confused.

Actually, we can migrate `sqlite3` to `sled`, and we will not need these dependencies anymore~

**Comment by gopricy** [comment]
any update on this bug, I encoutered it as well

**Comment by corporal9736** [comment]
I sloved this by using the version in rust-toolchain.
the exact command is
```
rustup install nightly-2021-05-16
rustup show
rustup default nightly-2021-05-16-x86_64-unknown-linux-gnu
cargo install leetcode-cli
```
You need to replace the "nightly-2021-05-16-x86_64-unknown-linux-gnu" by what you see in command "rustup show".
Maybe there are some difference in different versions.

**Comment by poly000** [comment]
How about use `.ok_or_else(OPTION_PARSER)?`

**Comment by clearloop** [comment]
> How about use `.ok_or_else(OPTION_PARSER)?`

This will work for this issue
