### ISSUE TITLE
no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope

### ISSUE THREAD

**Issue by poly000** [clearloop/leetcode-cli#45]
no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope

toolchain: `nightly-2021-05-16-x86_64-unknown-linux-gnu`

proc-macro2: 1.0.29 https://github.com/dtolnay/proc-macro2/issues/297

should fix #37 for newer toolchain support, or specify the use of proc-macro2 previous version?

**Comment by mqnfred** [comment]
For anybody encountering this issue, I personally solved it by cloning the repository, applying the following diff and then installing off of that:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 69758ac..520dae6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -32,6 +32,7 @@ serde = { version = "1.0.104", features = ["derive"] }
 serde_json = "1.0.44"
 toml = "0.5.5"
 regex = "1"
+proc-macro2 = "=1.0.26"
 
 [dependencies.diesel]
 version = "1.4.3"
```

```
britney:~/f/p/leetcode-cli$ rustup default
nightly-x86_64-unknown-linux-gnu (default)
britney:~/f/p/leetcode-cli$ cargo install --path .
```

**Comment by Gongsta** [comment]
> For anybody encountering this issue, I personally solved it by cloning the repository, applying the following diff and then installing off of that:
> 
> ```diff
> diff --git a/Cargo.toml b/Cargo.toml
> index 69758ac..520dae6 100644
> --- a/Cargo.toml
> +++ b/Cargo.toml
> @@ -32,6 +32,7 @@ serde = { version = "1.0.104", features = ["derive"] }
>  serde_json = "1.0.44"
>  toml = "0.5.5"
>  regex = "1"
> +proc-macro2 = "=1.0.26"
>  
>  [dependencies.diesel]
>  version = "1.4.3"
> ```
> 
> ```
> britney:~/f/p/leetcode-cli$ rustup default
> nightly-x86_64-unknown-linux-gnu (default)
> britney:~/f/p/leetcode-cli$ cargo install --path .
> ```

Still had this error after trying this out. I'm running Ubuntu on WSL.
```/usr/bin/ld: cannot find -ldbus-1
/usr/bin/ld: cannot find -lsqlite3```

I fixed it by running
```sudo apt install libdbus-1-dev
`sudo apt install libsqlite3-dev```

and it finally installed without errors! Hope this helps anyone who has similar issues
