### ISSUE TITLE
error while decoding response on linux

### ISSUE THREAD

**Issue by poly000** [clearloop/leetcode-cli#54]
running this:
`leetcode exec 1929`

results:
[`error: error decoding response body: expected value at line 1 column 1, please try again`](https://fars.ee/AOCZ66OHmCY0GtDxtKVsdth1N_UG)

[leetcode.toml](https://fars.ee/ACHQVkBdD6hPAzM6ytiMsMtTvFb4)

version: leetcode-cli 0.3.10(git build)

**Comment by poly000** [comment]
It seems that this issue was caused by mail verfication

**Comment by clearloop** [comment]
you can debug it with `leetcode -d exec 1929`
