### ISSUE TITLE
error: expected value at line 1 column 1

### ISSUE THREAD

**Issue by hao-lee** [clearloop/leetcode-cli#55]
Hello, I encountered a strange problem... Can't figure out what's wrong 😢 ... Thanks.
```
~# leetcode pick 55
~# leetcode edit 55 # add a line: return True
~# leetcode test 55
[INFO  leetcode_cli::plugins::leetcode] Sending code to judge...
error: expected value at line 1 column 1
```

**Comment by hao-lee** [comment]
Solved. The root cause is my cookie is expired. Maybe we can output some possible reasons in this error message to help users to figure out what's wrong.

**Comment by bulletmark** [comment]
OP, you should re-open this as it is a valid bug. "error: expected value at line 1 column 1" is not a clear message that the users cookie has expired, particularly when it will happen quite frequently.

**Comment by clearloop** [comment]
this error emits from parsing json response failed, if you run commands with `-d` flag, you can see the detail of the error

btw we definitely should optimize this

**Comment by hao-lee** [comment]
@bulletmark Yeah. This does make sense.
@clearloop Yes, `-d` definitely shows the failed line, although it doesn't give more information about how to solve the problem. I was inspired by other closed issues. Any exception that can corrupt the json response can lead to this error. Let me re-open this issue 😏

**Comment by clearloop** [comment]
https://github.com/clearloop/leetcode-cli/pull/67
