### ISSUE TITLE
Pick fails to parse 1214 json response.

### ISSUE THREAD

**Issue by jay1999ke** [clearloop/leetcode-cli#57]
Error thrown:
```
$ leetcode pick 1214

[1214] Two Sum BSTs is on the run...


json from response parse failed, please open a new issue at: https://github.com/clearloop/leetcode-cli/.```

**Comment by jay1999ke** [comment]
.

**Comment by bulletmark** [comment]
@jay1999ke why did you close this? Still happens for me.

**Comment by hao-lee** [comment]
1214 is a premium problem, you can't fetch it unless you upgrade your account.

**Comment by bulletmark** [comment]
@hao-lee that may be true but it is almost irrelevant to this issue. The error message implies the program is not handling the leetcode response correctly and thus it should be fixed.

We could close this issue then the next new user who comes along and hits this error will likely do exactly what the error message tells him, i.e come here and raise another new bug. Is that what we want?
