### ISSUE TITLE
"leetcode list" output should be sorted.

### ISSUE THREAD

**Issue by kgfly** [clearloop/leetcode-cli#64]
Observed
Currently, it's not sorted. Etc

        [2224] Minimum Number of Operations to Convert Time                 Easy   (61.81 %)
  🔒    [2214] Minimum Health to Beat Game                                  Medium (58.87 %)
  🔒    [2219] Maximum Sum Score of Array                                   Medium (66.86 %)
  🔒    [2228] Users With Two Purchases Within Seven Days                   Medium (47.86 %)
  🔒    [2230] The Users That Are Eligible for Discount                     Easy   (49.48 %)
  🔒    [2238] Number of Times a Driver Was a Passenger                     Medium (80.36 %)
        [2235] Add Two Integers                                             Easy   (93.47 %)
        [2236] Root Equals Sum of Children                                  Easy   (91.30 %)
  🔒    [2237] Count Positions on Street With Required Brightness           Medium (72.88 %)

Expected:
It should be sorted.

Thanks.

**Comment by clearloop** [comment]
Hi @kgfly , please try with 

```
leetcode list -qL 
```

**Comment by kgfly** [comment]
I notice that "leetcode list -qL" has removed the premium symbol, etc

![image](https://user-images.githubusercontent.com/12282281/163687276-71a75d6b-60d3-471b-88d8-7bbe483fff2b.png)

Is it possible the keep the symbol?

**Comment by clearloop** [comment]
> I notice that "leetcode list -qL" has removed the premium symbol, etc

haha, sry, I misunderstood your issue at last time, thought you were confused with the locked problems lol

do u mean the number of issues? we can sort them at https://github.com/clearloop/leetcode-cli/blob/60a9e88f4a4d643b2f0762714fdc102b29cb77c3/src/cmds/list.rs#L190
