### ISSUE TITLE
/usr/bin/ld: cannot find -ldbus-1

### ISSUE THREAD

**Issue by SamDc73** [clearloop/leetcode-cli#65]
Trying to install it through cargo, but it's giving me this error message  :
```
  = note: /usr/bin/ld: cannot find -ldbus-1
          collect2: error: ld returned 1 exit status
          

error: failed to compile `leetcode-cli v0.3.10`, intermediate artifacts can be found at `/tmp/cargo-installMTRpnO`

Caused by:
  could not compile `leetcode-cli` due to previous error
```

cargo -V 
`cargo 1.60.0`

and I'm running Fedora 35

**Comment by JasonYangShadow** [comment]
not sure, but for me after installing the prerequisites mentioned, it works
```
# Required dependencies:
# 
#  gcc
#  libssl-dev
#  libdbus-1-dev
#  libsqlite3-dev
```

my cargo version:
```
➜  ~ cargo --version
cargo 1.60.0 (d1fd9fe 2022-03-01)
```

**Comment by clearloop** [comment]
> Trying to install it through cargo, but it's giving me this error message :
> 
> ```
>   = note: /usr/bin/ld: cannot find -ldbus-1
>           collect2: error: ld returned 1 exit status
>           
> 
> error: failed to compile `leetcode-cli v0.3.10`, intermediate artifacts can be found at `/tmp/cargo-installMTRpnO`
> 
> Caused by:
>   could not compile `leetcode-cli` due to previous error
> ```
> 
> cargo -V `cargo 1.60.0`
> 
> and I'm running Fedora 35

which os ru working on? please 

```
sudo apt install libdbus-1-dev
```

if ur working on debian/ubuntu
