### ISSUE TITLE
installation error on mac os 

### ISSUE THREAD

**Issue by lqlee** [clearloop/leetcode-cli#70]
~ > leetcode list 
error: missing field `sys` at line 2 column 1, Parse config file failed, 
leetcode-cli has just generated a new leetcode.toml at ~/.leetcode/leetcode_
tmp.toml, the current one at ~/.leetcode/leetcode.tomlseems missing some 
keys, please compare to the tmp one and add them up : )

~ > ls .leetcode                                                            
                                                                    
leetcode.toml

~ > cat .leetcode/leetcode.toml                                             
                                                             
[code]
 editor = "vim"
 lang = "java"

[cookies]
 csrf = "........"
 session = "........"

~ > cargo -V                                                                
                                                                   
cargo 1.61.0 (a028ae42f 2022-04-29)

~ > rustc -V                                                                
                                                                   
rustc 1.61.0 (fe5b13d68 2022-05-18)

~ > brew list                                                               
                                                                 
openssl@3  dbus        openssl@1.1    sqlite    

~ > gcc -v                                                                  
                                                                   
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx
-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/
include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

anything else I need to install or update ?
Thanks.

**Comment by 152334H** [comment]
> leetcode-cli has just generated a new leetcode.toml at ~/.leetcode/leetcode_
tmp.toml, the current one at ~/.leetcode/leetcode.tomlseems missing some
keys, please compare to the tmp one and add them up : )

1. delete ~/.leetcode/leetcode.toml
2. run leetcode list
3. edit ~/.leetcode/leetcode.toml to add [code] and [cookies]

**Comment by lqlee** [comment]
Thanks. those steps work.
better update the installation or update the error message for 'leetcode list'
