### ISSUE TITLE
Failed to parse json data

### ISSUE THREAD

**Issue by zshchun** [clearloop/leetcode-cli#82]
I met this message when pick a problem.

```sh
$ leetcode pick 694

[694] Number of Distinct Islands is on the run...

json from response parse failed, please open a new issue at: https://github.com/clearloop/leetcode-cli/.

$ leetcode --version
leetcode-cli 0.3.11
```

**Comment by zshchun** [comment]
Thanks!

**Comment by anstadnik** [comment]
Hi, I got the same issue. Is there any progress on this?

**Comment by wendajiang** [comment]
My account was not the premium, so can you offer more information in detail? 
By `RUST_LOG="trace" leetcode-cli -d pick 694`

**Comment by anstadnik** [comment]
It works for me on macOS, with leetcode 0.3.12.
I got this problem on Arch Linux, but I'm not sure what fixed it :)

**Comment by wendajiang** [comment]
If you want post a PR to fix it?

**Comment by anstadnik** [comment]
I mean, I didn't change anything.
It was either a change from Arch to macOS or bumping a version from 0.3.11 to 0.3.12 which fixed the issue.
