### ISSUE TITLE
Bug report: wrong code template for 122.best-time-to-buy-and-sell-stock-ii.cpp

### ISSUE THREAD

**Issue by theidexisted** [clearloop/leetcode-cli#92]
To reproduce:

```
leetcode e 122
```

We get the source file name: _~/.leetcode/code/122.best-time-to-buy-and-sell-stock-ii.cpp_

But with wrong content:

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<vector<int>> zigzagLevelOrder(TreeNode* root) {
        
    }
};
```

Find with version: leetcode-cli 0.3.11

**Comment by theidexisted** [comment]
I have checked the cached database file and see that the code template stored is wrong in the database. 

So maybe:
* Get wrong response from leetcode site
* Their are bugs in the cache generation code

**Comment by wendajiang** [comment]
Can you try run this command `leetcode data -u` ? And re-run `leetcode e 122`

**Comment by theidexisted** [comment]
> Can you try run this command `leetcode data -u` ? And re-run `leetcode e 122`

I have tried but still, get the same result. Thanks!

**Comment by wendajiang** [comment]
Remove the cache file and re-generate the cache is ok? As I can not reproduce this problem.

**Comment by theidexisted** [comment]
> Remove the cache file and re-generate the cache is ok? As I can not reproduce this problem.

Maybe you are using the dev branch(Not the same one as I used:0.3.11)

**Comment by wendajiang** [comment]
I use the master branch and build target. Indeed it is not the github release version.
